### ISSUE TITLE
Left-over version control markers in t/general/basic.t

### ISSUE THREAD

**Issue by jkeenan** [rra/podlators#17]
Today I began to synchronize the Perl core distribution with the most recent CPAN release of the podlators distribution.

In the most recent Perl production release, certain podlators test files were customized, *i.e.*, had been modified from the corresponding test files in previous CPAN versions.  So part of the "sync-with-cpan" process is to decide which customizations should be retained and which should be removed in favor of the most recent CPAN versions.  Other things being equal, we'd prefer **not** to customize any files in the core.

I did a `vimdiff` comparison on the core and CPAN versions of `t/general/basic.t` and noticed what I suspect are commented-out version control markings in that file in https://cpan.metacpan.org/authors/id/R/RR/RRA/podlators-5.00.tar.gz.
```
 45 # Hard-code configuration for Term::Cap to get predictable results.
 46 #<<<
 47 local $ENV{COLUMNS}  = 80;
 48 local $ENV{TERM}     = 'xterm';
 49 local $ENV{TERMPATH} = File::Spec->catfile('t', 'data', 'termcap');
 50 local $ENV{TERMCAP}  = 'xterm:co=#80:do=^J:md=\\E[1m:us=\\E[4m:me=\\E[m';
 51 #>>>
 52 
 53 # Find the source of the test file.
 54 my $input = File::Spec->catfile('t', 'data', 'basic.pod');
 55 
 56 # Map of translators to the file containing the formatted output to compare
 57 # against.
 58 #<<<
 59 my %output = (
 60     'Pod::Man'              => File::Spec->catfile('t', 'data', 'basic.man'),
 61     'Pod::Text'             => File::Spec->catfile('t', 'data', 'basic.txt'),
 62     'Pod::Text::Color'      => File::Spec->catfile('t', 'data', 'basic.clr'),
 63     'Pod::Text::Overstrike' => File::Spec->catfile('t', 'data', 'basic.ovr'),
 64     'Pod::Text::Termcap'    => File::Spec->catfile('t', 'data', 'basic.cap'),
 65 );
 66 #>>>
```
Assuming that these are indeed just left-over version control marks, could you remove them and issue a new CPAN release (which I would then synch into Perl 5 blead)?

Thank you very much.
Jim Keenan

**Comment by rra** [comment]
Thanks for the very thorough review! Yes, please do send me any changes in Perl core that are lingering. I will happily include them in the next release and cut a new release quickly to ease the reconciliation process.

In this case, these markings are intentional. They're unrelated to version control software; they're "leave this formatting alone" markers for perltidy. See https://metacpan.org/dist/Perl-Tidy/view/bin/perltidy#Skipping-Selected-Sections-of-Code

**Comment by jkeenan** [comment]
> Thanks for the very thorough review! Yes, please do send me any changes in Perl core that are lingering. I will happily include them in the next release and cut a new release quickly to ease the reconciliation process.
> 
> In this case, these markings are intentional. They're unrelated to version control software; they're "leave this formatting alone" markers for perltidy. See https://metacpan.org/dist/Perl-Tidy/view/bin/perltidy#Skipping-Selected-Sections-of-Code

So, you're saying that there's no harm in including them in the version of `t/general/basic.t` that gets shipped with Perl core -- correct?

**Comment by rra** [comment]
Yes, correct. They're just comments to Perl.
