### ISSUE TITLE
Exit status different between pod2man and pod2text

### ISSUE THREAD

**Issue by Julien-Elie** [rra/podlators#19]
I wish to test the availability of `--guesswork` by trying the argument and checking the exit status but unfortunately `pod2text` works differently than `pod2man`:

```
% pod2man --help > /dev/null
% echo $?
0

% pod2text --help > /dev/null
% echo $?
1
```

So if I add `--guesswork=none`, I cannot distinguish the availability of it with `pod2text`.

Seems like I should better use for the test:

`echo "=head1 test" | pod2text --guesswork=none > /dev/null`

And that's what I'll do.  However, homogenizing exit status (either to `0` or `1`) would be great.

**Comment by rra** [comment]
Thanks! No idea why it was like that, and it definitely shouldn't have been.
