### ISSUE TITLE
Piping POD into pod2man fails as of last release

### ISSUE THREAD

**Issue by ingydotnet** [rra/podlators#2]
```
printf '=pod\n\n=head1 Hello\n\n=cut\n' | pod2man ; echo $?
```

This is breaking my:

```
swim --to=man ...
```

which is breaking a lot of my stuff that depends on that.

**Comment by rra** [comment]
`-n` is a required option when feeding documents into standard input as of podlators 4.00.  This is documented in the man page as well.  Apologies for the backward-incompatible change; it was the best fix that I could come with to the requirements of the *roff format for valid `.TH` lines that would produce the least unexpected behavior.
