### ISSUE TITLE
S< non-breaking text > does not work with Pod::Text::Color

### ISSUE THREAD

**Issue by jimav** [rra/podlators#24]
Hi, Text in S<...> is not supposed to be wrapped but something Pod::Text::Color does seems to defeat this, at least when used via `perldoc`.

Please see the bug filed against 'perldoc' which now seems to be caused by Pod::Text::Color 

https://github.com/briandfoy/pod-perldoc/issues/55

Thanks.

**Comment by rra** [comment]
Thanks for the report! This was specific to Pod::Text subclasses with documents that used a UTF-8 input encoding. It should be fixed in the next podlators release.
