### ISSUE TITLE
Change in Perl 5 blead causing failures in t/man/devise-date.t

### ISSUE THREAD

**Issue by jkeenan** [rra/podlators#27]
A change in Perl 5 blead is causing intermittent test failures in `t/man/devise-date.t`, both within the core distribution's smoke-testing and [on CPAN](http://fast-matrix.cpantesters.org/?dist=podlators;perl=5.39.9;reports=1).  Please see the ongoing discussion in https://github.com/Perl/perl5/issues/22062.

**Comment by rra** [comment]
Thanks for the heads up. It never occurred to me that strftime wouldn't work with the results of gmtime, but after reading this, I can see why it's not entirely clear whether this is correct behavior. It's easy enough to avoid using strftime in the podlators test suite, so I'll just do that.

**Comment by rra** [comment]
After thinking about this some more and reviewing https://github.com/Perl/perl5/issues/22062, I've convinced myself that this caught a real regression in Perl. So, for the record, I restored the previous test for the next release.
