### ISSUE TITLE
Changes for .IX handling seem to have silenced the output

### ISSUE THREAD

**Issue by guillemj** [rra/podlators#3]
I was checking git master (commit 74b5c541795332e37e187d8a06d9ab7be27227b8), and noticed that it does not generate any output anymore. On an up-to-date Debian sid system, from a git clone:

  `$ PERL5LIB=blib/lib blib/script/pod2man $(perldoc -l perl) | man -l -`

produces nothing. After reverting b98b04e3557a7f241a82a185f21c74f7a173d02c and 5f98aa66cf327a0bc8d319704700a4c38c86773c it seems to work again.

**Comment by rra** [comment]
Whoops, thank you, fixed in 665e4e8c.
